apiVersion: v2
appVersion: "1.0"
description: Family Private Law - Notification Service
name: prl-rpa
version: 0.0.1
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
