java:
  environment:
    MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
    DOCMOSIS_SERVICE_DEV_MODE_FLAG: "false"
    PDF_TEST_ENABLED: "false"

  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName: prl
